### ISSUE TITLE
ability to copy all files that are currently open in tabs

### ISSUE THREAD

**Issue by avidh** [jbaranski/TossFile#1]
Hi there,
I was looking for a plugin that can quickly copy selective/open files from current project to a different locations by relative path and TossFile is the only one that came close to what I needed.

However, looks like your plugin can only copy one file at a time... could you please add option to copy all currently open files as well? 

For example, I'm also using SFTP plugin and it has the ability to upload current file or all open files using a different shortcut keys.

Thank you so much for this wonderful plugin and I will use this to copy one file at at time but please do consider adding this nice feature to copy all open files as well.

Thank you and Merry Christmas!

**Comment by jbaranski** [comment]
I will work on getting a config property added in that will turn this on. Sorry for the late reply GitHub didn't send me a notification this issue was created. Thanks for the feedback.

**Comment by jbaranski** [comment]
I added a second context menu item, "Toss All Files", that works exactly the same as "Toss File" context menu item, except it runs against all open files (instead of having to do each manually).

Let me know if that is good for you or you were thinking of anything else?

**Comment by avidh** [comment]
Thank you so much!  It's working as expected and this extension will be one of my favorites.
I do have few more suggestions so I will create tickets for them later but they are not as important or nice to have so no big deal but this particular "Toss All Files" was a big enhancement for me.

No problem about late reply. I figured you were busy since this ticket was opened during holiday season. Thanks again for this awesome extension and this enhancement. Cheers!
