### ISSUE TITLE
some sort of visual indicator that TossFile executed

### ISSUE THREAD

**Issue by avidh** [jbaranski/TossFile#2]
This is not that big deal but it will save some time and give a peace of mind.
Now that I have awesome new "Toss All File"s feature and have bound to set of keys, I often use the ctrl+alt+shift+t to Toss current file or ctrl+alt+shift+a to Toss all opened files to designated locations.

I know this awesome extension works as expected when executed but I question myself if I had pressed the correct keys and if the command actually ran or not because there's no status or indicator whatsoever that this wonderful package that executed.
So, I keep going back to other mapped folders and manually check to see if one of files got copied over (because I can't afford to not have those files copied over).

Again, I know this package works but I don't trust myself that I had pressed the correct keys or don't trust if SublimeText has executed the command or not :)

It would be great if there's some sort of visual indicator that the Toss File or Toss All Files has been executed.

Suggestion: display "Toss File (or Toss All Files) has been executed" in status bar and have it go away after few seconds.  If making it go away after few seconds is difficult than include sys timestamp with it so you know when it was executed.

Thanks!

**Comment by jbaranski** [comment]
I find myself doing the same thing (double checking the output folder) so this is a good idea, thanks for the feedback.

**Comment by jbaranski** [comment]
Before I commit this I would like your feedback. Screenshots below of what this would look like.
1. In the footer of the current view (the current file) an indicator of which command was run and how many times a file or files was copied to some new location based on the rules setup in your settings, including 0. I like this, do you agree?
2. The indicator will go away after 5 seconds. Seems like a decent amount of time but I want to see what you think.
3. The indicator only exists in the footer of the current file the command was run, so if you run the command and quickly switch tabs you will have to switch back to the tab that the command was run in to see the indicator (within 5 seconds of course). Is that alright?
4. Maybe in the future or under another issue I will explore if running "toss all files" to put this in the footer of all open files? Do you care about this?
5. Maybe in the future I will add a setting to control how many seconds the message stays up? Do you care about this?
6. Maybe in the future I will add a timestamp and make it possible the message never goes away? Do you care about this?

![image](https://cloud.githubusercontent.com/assets/10889950/12381091/d688fc54-bd50-11e5-8dad-b7341163d48e.png)

![image](https://cloud.githubusercontent.com/assets/10889950/12381096/f08a5f8a-bd50-11e5-928a-612718f1da6f.png)

Anyway thanks again for your feedback!

**Comment by avidh** [comment]
Thanks for considering this enhancement and also for asking my feedback :)
1. Yes, I like it! especially the fact that it will include 0 (because this means the file did not match any setting)
2. Yes, I think 5 seconds is good.  It's not too short while not too long in case you want to execute the command again.
3. I don't see any problem with this because I just need a visual indicator right after I run the commands so I will always look for this status in the footer after I run the command and once I confirm/see it, I probably will not look at it again whether I stay on the same file or move to another file/tab until I'm ready to run the command again. 
   This feature is for instant confirmation/gratification that the command executed so no need to worry about other tabs in my opinion.
4. I don't think this is necessary in my opinion because of reason I gave in #3 above.
5. This might be a nice-to-have feature for somebody but I don't think it's a priority/urgent.
6. This might be another nice option to have for somebody but I don't think it's that important.  I only suggested this option in case making the status automatically go away was difficult.

Quick questions/feedback about status message:
1. I think it would look nicer if it said "Toss All Files: tossed 2 file(s)" or "Toss All Files: 2 file(s) tossed" rather than "Toss All Files: 2 tossed file(s)".  Similar change for single file status.
2. If 1 file was copied over to three different locations based on setting, would it say 1 file? or 3 files?
   I think it would be super nice if it said "tossed 1 file(s) to 3 locations" but again this is just another nice to have.

Thanks again and please let me know if you have any question. Cheers!

**Comment by jbaranski** [comment]
From my points above:
1. Done
2. Done, 5 seconds is the default. You can modify statusTimeout setting to modify this if you wish
3. OK the status will only show up in this current file the command was run in, it's fine with me as well
4. I didn't really think it was necessary either, so did not explore this
5. I went ahead and did this since it was easy and nice to have
6. I didn't really think this was necessary either, if you change your mind and want it later just let me know.

Your points above:
1. Good call, I added in your suggestion
2. In the scenario you describe it would end up saying 3 files, I agree it would be kind of confusing. Good call, I added in your suggestion.

Alright I published a new release, can you take a look, if everything looks good to you I will close this issue.

Thanks again for the great suggestions, they will be useful for me and my workflow as well.

**Comment by avidh** [comment]
Thanks again. Works like a charm! Cheers!
