### ISSUE TITLE
enhancement to exclude copy all files currently open

### ISSUE THREAD

**Issue by avidh** [jbaranski/TossFile#3]
Hi there, 
It's been over 2 years since I requested 2 enhancement, which you provided.
TossFile is still one of my favorite sublime text plugin and I use it manage multiple projects that are using the same code base.

I was wondering if it's possible to add "exclusion_paths" in the setting so that all currently open files would get tossed based on "paths" setting UNLESS the file is located inside the "exclusion_paths" folders.

If it's easier, I can also work with "exclusion_files" setting where I can specify specific files that should never get tossed...

Thanks and hope all is well. 
Cheers!

**Comment by jbaranski** [comment]
Hi,

I was pondering recently adding an excludes path for each entry coincidentally, and also a global file extension exclude setting and allow that to be overridden per mapping if needed as well.

Will take a look this weekend. Thanks for the feedback.

**Comment by jbaranski** [comment]
I can also add a global file name excludes too and allow that to be overridden, good idea. Will let you know.

**Comment by avidh** [comment]
Great, thanks!
For me, global file name excludes will be much more helpful for my use case but I'm sure other users might consider exclude paths more useful.

BTW, when you get to this, it would be very helpful to also update the status message to show how many files were ignored (or not tossed) because of the exclusion setting.

Thanks again.
David

**Comment by jbaranski** [comment]
Hi,

I added replaceIfExists, extensionExcludes, nameExcludes, pathExcludes options, also the output string will reflect number of files / locations skipped if those settings above are hit. Can you take a look at the read me and see if this meets your needs?

**Comment by avidh** [comment]
Hi,
I was out of town over the weekend so I got to test this feature today and it works wonderfully!
Thank you so much!  TossFile is now more powerful than ever.

My only feedback, which is not that big of a deal, is that "pathExcludes" setting is based on destination path rather than the source path.  For my project, I have 1 master source project that gets copied to multiple destination paths so I have to repeat and include multiple pathExcludes for each destination rather than simply having 1 master/source pathExcludes.
However, I can see that your current implementation might provide more control and flexibility for other use cases so that's why this is not a big deal.  Thanks again for quick turn around on this enhancement!
Cheers!

**Comment by jbaranski** [comment]
Sure, interestingly enough I mainly use the opposite scenario. I can add an inputPathExcludes option as well, I'll do that next weekend.

**Comment by avidh** [comment]
wow.. you are awesome... thanks again and I can use the "pathExcludes" to work around my use case so there's really no rush for you to work on it next weekend. :)
Cheers!

**Comment by jbaranski** [comment]
Hi,

I added inputPathExcludes option, rename pathExcludes option to outputPathExcludes option.

The option rename is a backward compatibility breaking change but necessary because it was naively named.

Let me know if you run into any issues.

**Comment by avidh** [comment]
Thank you so much! Works as intended.
You have made my workflow more efficient by like 200% :)

**Comment by jbaranski** [comment]
Cool, glad I could help. Let me know if you come up with any other ideas.
